silly_string_1 = "Hey diddle diddle the %s and the %s the %s %s over the %"
silly_string_2 = "%s and %s went up a %s to fetch a %s of %s"
silly_string_3 = "%s had a %s %s whose %s was &s as %s"
silly_string_4 = "If you're %s and you know it %s your %s"
silly_string_5 = "The %s %s %s %s and %s and %s the %s down"
silly_string_6 = "%s, %s, %s %s have you any %s?"
